apiVersion: batch/v1
kind: CronJob
metadata:
  name: db-backup-cronjob
spec:
  schedule: "*/2 * * * *" 
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: db-backup
              image: eseynoa/cron-backup:latest
              imagePullPolicy: Always
              command: ["node", "/app/backup-script.js"]
          restartPolicy: OnFailure
